### ISSUE TITLE
Build issue on Render.com

### ISSUE THREAD

**Issue by danisaza** [render-examples/gatsby-starter-default#10]
I've been experiencing build issues with my personal site ([GitHub repo here](https://github.com/danisaza/personal-site)), which is a simple fork of this repo.

I first noticed this build issue on October 27th, when I saw the following errors in my build on Render.com:
```
Oct 27 05:01:55 PM  ==> Cloning from https://github.com/danisaza/gatsby-starter-default...
Oct 27 05:01:56 PM  ==> Checking out commit 6d3bc92d9ddb8333adc5e938e77b534dcb6b1cda in branch reading
Oct 27 05:01:59 PM  ==> Installing dependencies with Yarn...
Oct 27 05:01:59 PM  yarn install v1.19.1
Oct 27 05:01:59 PM  warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
Oct 27 05:01:59 PM  [1/4] Resolving packages...
Oct 27 05:02:01 PM  [2/4] Fetching packages...
Oct 27 05:02:33 PM  info fsevents@1.2.4: The platform "linux" is incompatible with this module.
Oct 27 05:02:33 PM  info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
Oct 27 05:02:33 PM  [3/4] Linking dependencies...
Oct 27 05:02:47 PM  [4/4] Building fresh packages...
Oct 27 05:02:54 PM  error /opt/render/project/src/node_modules/sharp: Command failed.
Oct 27 05:02:54 PM  Exit code: 1
Oct 27 05:02:54 PM  Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Oct 27 05:02:54 PM  Arguments:
Oct 27 05:02:54 PM  Directory: /opt/render/project/src/node_modules/sharp
Oct 27 05:02:54 PM  Output:
Oct 27 05:02:54 PM  info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
Oct 27 05:02:54 PM  make: Entering directory '/opt/render/project/src/node_modules/sharp/build'
Oct 27 05:02:54 PM    TOUCH Release/obj.target/libvips-cpp.stamp
Oct 27 05:02:54 PM    CXX(target) Release/obj.target/sharp/src/common.o
Oct 27 05:02:54 PM  In file included from ../../nan/nan_new.h:189,
Oct 27 05:02:54 PM                   from ../../nan/nan.h:223,
Oct 27 05:02:54 PM                   from ../src/common.cc:24:
Oct 27 05:02:54 PM  ../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
Oct 27 05:02:54 PM  ../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
Oct 27 05:02:54 PM     return v8::StringObject::New(value).As<v8::StringObject>();
Oct 27 05:02:54 PM                                       ^
Oct 27 05:02:54 PM  In file included from /opt/render/.cache/12.13.0/include/node/node.h:63,
Oct 27 05:02:54 PM                   from ../src/common.cc:22:
Oct 27 05:02:54 PM  /opt/render/.cache/12.13.0/include/node/v8.h:5426:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
Oct 27 05:02:54 PM     static Local<Value> New(Isolate* isolate, Local<String> value);
Oct 27 05:02:54 PM                         ^~~
Oct 27 05:02:54 PM  /opt/render/.cache/12.13.0/include/node/v8.h:5426:23: note:   candidate expects 2 arguments, 1 provided
```

Since then, I've been experiencing more issues on PR preview builds from Render.

Today I experienced the same error on a more recent PR to the repo. I removed the `package-lock.json` and rebuilt the site. This yielded the errors shown below.
```
Nov 7 10:05:27 PM  ==> Cloning from https://github.com/danisaza/gatsby-starter-default...
Nov 7 10:05:28 PM  ==> Checking out commit acb48025b818e4149c95a50d94df0db2003c262a in branch reading-updates
Nov 7 10:05:31 PM  ==> Installing dependencies with Yarn...
Nov 7 10:05:32 PM  yarn install v1.19.1
Nov 7 10:05:32 PM  [1/4] Resolving packages...
Nov 7 10:05:33 PM  [2/4] Fetching packages...
Nov 7 10:06:08 PM  info fsevents@1.2.4: The platform "linux" is incompatible with this module.
Nov 7 10:06:08 PM  info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
Nov 7 10:06:08 PM  [3/4] Linking dependencies...
Nov 7 10:06:22 PM  [4/4] Building fresh packages...
Nov 7 10:06:30 PM  error /opt/render/project/src/node_modules/sharp: Command failed.
Nov 7 10:06:30 PM  Exit code: 1
Nov 7 10:06:30 PM  Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Nov 7 10:06:30 PM  Arguments:
Nov 7 10:06:30 PM  Directory: /opt/render/project/src/node_modules/sharp
Nov 7 10:06:30 PM  Output:
Nov 7 10:06:30 PM  info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
Nov 7 10:06:30 PM  make: Entering directory '/opt/render/project/src/node_modules/sharp/build'
Nov 7 10:06:30 PM    TOUCH Release/obj.target/libvips-cpp.stamp
Nov 7 10:06:30 PM    CXX(target) Release/obj.target/sharp/src/common.o
Nov 7 10:06:30 PM  In file included from ../../nan/nan_new.h:189,
Nov 7 10:06:30 PM                   from ../../nan/nan.h:223,
Nov 7 10:06:30 PM                   from ../src/common.cc:24:
Nov 7 10:06:30 PM  ../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
Nov 7 10:06:30 PM  ../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
Nov 7 10:06:30 PM     return v8::StringObject::New(value).As<v8::StringObject>();
Nov 7 10:06:30 PM                                       ^
Nov 7 10:06:30 PM  In file included from /opt/render/.cache/12.13.0/include/node/node.h:63,
Nov 7 10:06:30 PM                   from ../src/common.cc:22:
Nov 7 10:06:30 PM  /opt/render/.cache/12.13.0/include/node/v8.h:5426:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
Nov 7 10:06:30 PM     static Local<Value> New(Isolate* isolate, Local<String> value);
Nov 7 10:06:30 PM                         ^~~

.... (more error logs that I've omitted for readability) ....

Nov 7 10:06:30 PM  ../src/common.cc:51:71: error: ‘buffersToPersist’ was not declared in this scope
Nov 7 10:06:30 PM       v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
Nov 7 10:06:30 PM                                                                         ^~~~~~~~~~~~~~~~
Nov 7 10:06:30 PM  make: *** [sharp.target.mk:136: Release/obj.target/sharp/src/common.o] Error 1
Nov 7 10:06:30 PM  gyp ERR! build error
Nov 7 10:06:30 PM  gyp ERR! stack Error: `make` failed with exit code: 2
Nov 7 10:06:30 PM  gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
Nov 7 10:06:30 PM  gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
Nov 7 10:06:30 PM  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Nov 7 10:06:30 PM  gyp ERR! System Linux 4.15.0-1044-gke
Nov 7 10:06:30 PM  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Nov 7 10:06:30 PM  gyp ERR! cwd /opt/render/project/src/node_modules/sharp
Nov 7 10:06:30 PM  gyp ERR! node -v v12.13.0
Nov 7 10:06:30 PM  gyp ERR! node-gyp -v v5.0.5
Nov 7 10:06:30 PM  gyp ERR! not ok
Nov 7 10:06:30 PM  make: Leaving directory '/opt/render/project/src/node_modules/sharp/build'
Nov 7 10:06:30 PM  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Running `gastby build` locally results in a totally fine build (both with and without the `package-lock.json` file present).

Here are some details about the versions of tools I have on my local machine:
```
yarn -v
1.9.4

node -v
v10.15.0

gatsby -v
2.6.2
```

Let me know if there are other details that would be helpful for me to provide!

**Comment by danisaza** [comment]
Oh, also - I found [this StackOverflow post](https://stackoverflow.com/questions/58085604/docker-build-fails-in-gcp-cloud-build-but-successful-in-localhost) that seems to reference a failing build on GCP that works on localhost. It links to [this GitHub Issue](https://github.com/mapbox/node-pre-gyp/issues/477) for `node-pre-gyp`, which references using `--fallback-to-build` on certain dependencies as a possible solution.

I haven't dug super deeply into this build issue yet, and I'm not feeling any super critical pain around it. (I can't update my reading list on my personal site, but hey - that's okay).

However, I'm wondering if other folks who forked this repo for their Gatsby sites on Render are having similar problems.

**Comment by anurag** [comment]
Thanks for flagging. This was an issue with old dependencies. The latest version (pushed a few hours ago) works as-is on Render!

**Comment by danisaza** [comment]
Thanks, Anurag!

**For anyone reading along here:**
Since the issue is resolved in the repo that I forked from, I resolved the issue on my own fork of the repo by syncing my fork ([instructions here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)).
